name: yeast_cell
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.2.0
  - pytorch::torchvision=0.17.0
  - pytorch::torchaudio=2.2.0
  - pytorch::pytorch-cuda=12.4
  - numpy=1.26.3
  - opencv=4.8.1
  - albumentations=1.3.1
  - matplotlib=3.8.2
  - tqdm=4.66.1
  - scipy=1.11.4
  - pandas=2.1.4
  - scikit-learn=1.3.2
  - scikit-image=0.22.0
  - tensorboard=2.15.1
  - pip=23.3.1
  - pip:
    - opencv-python==4.8.1.78
    - pillow==10.1.0
    - pyyaml==6.0.1
    - wandb==0.16.1
    - onnx==1.15.0
    - onnxruntime-gpu==1.16.3
    - imgaug==0.4.0
    - labelme==5.3.1
    - imageio==2.31.1
