inference:
  # 基本参数
  confidence_thresh: 0.15      # 较低的置信度阈值，适合小目标
  iou_thresh: 0.45            # NMS IoU阈值
  device: "cuda:0"            # 推理设备
  batch_size: 4               # 批处理大小
  img_size: [640, 640]        # 输入图像大小
  
  # 预处理
  preprocess:
    normalize: true           # 是否归一化
    means: [0.485, 0.456, 0.406]
    stds: [0.229, 0.224, 0.225]
    scale_fill: false         # 缩放填充方式
    auto_size: true           # 自动调整大小
  
  # 后处理
  postprocess:
    use_nms: false            # 不使用NMS，直接使用TopK选择
    use_topk: true            # 使用TopK选择
    topk: 100                 # TopK数量
    min_area: 1               # 最小目标面积（降低以检测更小的目标）
    max_area: 0.8             # 最大目标面积（相对于图像）
  
  # TensorRT配置
  tensorrt:
    engine_file: "exported_models/yolov10_yeast_fp16.trt"
    precision: "fp16"         # 精度模式: fp32, fp16, int8
    workspace_size: 4         # 工作区大小(GB)
    dynamic_batch: true       # 是否使用动态批处理大小
    max_batch_size: 16        # 最大批处理大小
    profile_shapes:           # 输入形状配置
      min: [1, 3, 640, 640]
      opt: [4, 3, 640, 640]
      max: [16, 3, 640, 640]
  
  # 可视化
  visualization:
    enable: true              # 是否开启可视化
    line_thickness: 2         # 边框线条粗细
    text_scale: 0.5           # 文本缩放
    colormap: "rainbow"       # 颜色映射
    draw_scores: true         # 是否显示置信度分数
    class_names: ["酵母细胞"] # 类别名称
    save_dir: "inference_results"
    
  # 性能测试
  benchmark:
    enable: true              # 是否进行性能测试
    warmup_runs: 50           # 预热运行次数
    num_runs: 1000            # 测试运行次数
    log_interval: 100         # 日志记录间隔 